title: Idea Graveyard
author: VB
email: vlasisbechrakis@gmail.com
# Site settings
description: >-
  Exploring the analytical engine, poetry, and the intersection of art and science.
url: "https://JohnsonArnek.github.io" # Assuming this is a user page
baseurl: ""

# Theme
theme: minima

# Minima specific settings
minima:
  social_links:
    github: adalovelace
    # Add other social links

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Header navigation pages (for Minima theme)
header_pages:
  - about.md
  - blog.md
  - projects.md

# Build settings (you might not need to change these for now)
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown features
  hard_wrap: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list of excluded items for the build.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
