title: Idea Graveyard
author: VB
email: vlasisbechrakis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A space for my random writings and a showcase of my projects.
url: "https://JohnsonArnek.github.io" # Replace with your actual GitHub Pages URL
                                     # If it's a project page: https://your-username.github.io/your-repo-name
baseurl: "" # If your site is at the root (e.g., your-username.github.io), leave this empty.
            # If it's in a subfolder (e.g., your-username.github.io/my-blog), set it to "/my-blog".

# Minima theme specific (if you're using Minima)
minima:
  # Minima specific settings can go here, like social links
  social_links:
    twitter: your_twitter_username
    github: your_github_username
    # linkedin: your_linkedin_username
    # dribbble: your_dribbble_username
    # etc.
