# Site settings
title: Idea Graveyard
author: VB
email: vlasisbechrakis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to VB's Idea Graveyard – a space for exploring side projects, art, AI, writing, coding,
  business, economics, reading, politics, history, technological progress, and the myriad of
  ideas that spring from a Jack of all trades. Dive into a diverse collection of thoughts and creations.
# social_links: # You can uncomment and add these later if you decide to
  # twitter: your_twitter_username
  # github:  your_github_username # You can add this later when you decide which account
  # linkedin: your_linkedin_profile

# GitHub Pages URL and BaseURL settings
# For a user/organization site like https://johnsonarnek.github.io/
# the repository name MUST BE JohnsonArnek.github.io
url: "https://johnsonarnek.github.io"
baseurl: "" # For a user/organization site at the root, baseurl is an empty string

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Header navigation pages (for Minima theme)
header_pages:
  - about.md
  - blog.md      # For your "Writings"
  - projects.md  # For your "Side Projects"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown features like tables, fenced code blocks
  hard_wrap: false # Set to true if you want single newlines in Markdown to become <br> tags

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list of excluded items for the build.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
  # - .github/ # If you don't want workflow files in the final site (usually not needed to exclude)
